const data = {
    products:[
        {
            _id:'1',
            name:'Chicklet Normalsize White',
            category:'Chicken',
            Image:'/img/product_sample.jpg',
            price: 120,
            brand: 'Natural',
            rating: 4.5,
            numReviews:10,
            description: "High quality chicklet",
        },
        {
            _id:'1',
            name:'Chicklet Normalsize White',
            category:'Chicken',
            Image:'/img/product_sample.jpg',
            price: 120,
            brand: 'Natural',
            rating: 4.5,
            numReviews:10,
            description: "High quality chicklet",
        },
        {
            _id:'1',
            name:'Chicklet Normalsize White',
            category:'Chicken',
            Image:'/img/product_sample.jpg',
            price: 120,
            brand: 'Natural',
            rating: 4.5,
            numReviews:10,
            description: "High quality chicklet",
        },
        {
            _id:'1',
            name:'Chicklet Normalsize White',
            category:'Chicken',
            Image:'/img/product_sample.jpg',
            price: 120,
            brand: 'Natural',
            rating: 4.5,
            numReviews:10,
            description: "High quality chicklet",
        },
        {
            _id:'1',
            name:'Chicklet Normalsize White',
            category:'Chicken',
            Image:'/img/product_sample.jpg',
            price: 120,
            brand: 'Natural',
            rating: 4.5,
            numReviews:10,
            description: "High quality chicklet",
        },
    ],
};