const data = {
    products:[
        {
            _id:'1',
            name:'Chicklet Normalsize White',
            category:'Chicken',
            Image:'/img/product_sample.jpg',
            price: 120,
            brand: 'Natural',
            rating: 4.5,
            numReviews:10,
            description: "High quality chicklet",
        },
        {
            _id:'2',
            name:'Fake Chicken',
            category:'Chicken',
            Image:'/img/chicken2.svg',
            price: 12,
            brand: 'Rubber',
            rating: 40.5,
            numReviews:10,
            description: "Guaranteed authentic chicken",
        },
        {
            _id:'3',
            name:'Abstract Rooster Maya Style',
            category:'Chicken',
            Image:'/img/chicken3.svg',
            price: 220,
            brand: 'Abstract',
            rating: 2.5,
            numReviews:10,
            description: "Acquired taste chicken",
        },
        {
            _id:'4',
            name:'Glorious Rooster',
            category:'Chicken',
            Image:'/img/chicken4.svg',
            price: 99,
            brand: 'Natural',
            rating: 5.0,
            numReviews:10,
            description: "All baby chickens want to be him, all hens want him inside of them.",
        },
        {
            _id:'5',
            name:'Family Rooster',
            category:'Chicken',
            Image:'/img/chicken5.svg',
            price: 52,
            brand: 'Natural',
            rating: 4.0,
            numReviews:10,
            description: "He's not handsome, not very smart, not even rich. But hey, he is good with the chicklets and there when you need him.",
        },
    ],
};